on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: wlppoccicd.azurecr.io
        username: ${{ secrets.acr_wlppoccicd_username }}
        password: ${{ secrets.acr_wlppoccicd_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/." -f  "." -t wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }} --label dockerfile-path=.
        docker push wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wlppocaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wlp-poc-aks952b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wlp-poc-aks952b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wlp-poc-aks952b
        container-registry-url: wlppoccicd.azurecr.io
        container-registry-username: ${{ secrets.acr_wlppoccicd_username }}
        container-registry-password: ${{ secrets.acr_wlppoccicd_password }}
        secret-name: wlppocaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: wlp-poc-aks952b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          wlppoccicd.azurecr.io/wlppocaks:${{ github.sha }}
        imagepullsecrets: |
          wlppocaksdockerauth
